version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # B2 specific environment variables for model loading
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME:-lawlens-models}
      - MODEL_CACHE_DIR=/tmp
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - model_cache:/tmp/lawlens_models  # Cache B2 models here
      # Remove ./models volume since we're using B2 now
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=2
    env_file:
      - .env
    environment:
      # B2 environment variables for Celery workers too
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME:-lawlens-models}
      - MODEL_CACHE_DIR=/tmp
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - model_cache:/tmp/lawlens_models  # Shared model cache
    depends_on:
      - redis

  flower:
    image: mher/flower
    command: flower --broker=${REDIS_URL} --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - celery
      - redis

  # Add Redis service if not already defined elsewhere
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  model_cache:  # Shared volume for B2 model cache
  redis_data:   # Redis data persistence



