services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./cache:/app/cache

  celery:
    build: .
    command: celery -A celery_worker worker --loglevel=info --concurrency=2
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./cache:/app/cache

  flower:
    image: mher/flower
    command: flower --broker=${REDIS_URL} --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - celery

volumes:
  cache:
